<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260415140748 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE financial_models (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, short_id VARCHAR(10) NOT NULL, title VARCHAR(255) NOT NULL, version_number INT NOT NULL, status VARCHAR(32) NOT NULL, amount_display_format VARCHAR(16) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, project_id BIGINT NOT NULL, source_model_id BIGINT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX financial_models__project_id__idx ON financial_models (project_id)');
        $this->addSql('CREATE INDEX financial_models__project_id_status__idx ON financial_models (project_id, status)');
        $this->addSql('CREATE INDEX financial_models__source_model_id__idx ON financial_models (source_model_id)');
        $this->addSql('CREATE UNIQUE INDEX financial_models__short_id__uniq ON financial_models (short_id)');
        $this->addSql('CREATE UNIQUE INDEX financial_models__project_version_number__uniq ON financial_models (project_id, version_number)');
        $this->addSql('CREATE TABLE projects (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, short_id VARCHAR(10) NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, status VARCHAR(32) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, owner_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX projects__owner_id__idx ON projects (owner_id)');
        $this->addSql('CREATE INDEX projects__owner_id_status__idx ON projects (owner_id, status)');
        $this->addSql('CREATE UNIQUE INDEX projects__short_id__uniq ON projects (short_id)');
        $this->addSql('CREATE TABLE time_params (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, investment_start_month DATE NOT NULL, investment_duration_months INT NOT NULL, commercial_operation_duration_months INT NOT NULL, forecast_step VARCHAR(16) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, financial_model_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX time_params__financial_model_id__uniq ON time_params (financial_model_id)');
        $this->addSql('CREATE TABLE users (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSONB NOT NULL, password VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX users__email__uniq ON users (email)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE financial_models ADD CONSTRAINT FK_4F766CBA166D1F9C FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE financial_models ADD CONSTRAINT FK_4F766CBA3A558135 FOREIGN KEY (source_model_id) REFERENCES financial_models (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE projects ADD CONSTRAINT FK_5C93B3A47E3C61F9 FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE time_params ADD CONSTRAINT FK_D6384105D440FCE3 FOREIGN KEY (financial_model_id) REFERENCES financial_models (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE financial_models DROP CONSTRAINT FK_4F766CBA166D1F9C');
        $this->addSql('ALTER TABLE financial_models DROP CONSTRAINT FK_4F766CBA3A558135');
        $this->addSql('ALTER TABLE projects DROP CONSTRAINT FK_5C93B3A47E3C61F9');
        $this->addSql('ALTER TABLE time_params DROP CONSTRAINT FK_D6384105D440FCE3');
        $this->addSql('DROP TABLE financial_models');
        $this->addSql('DROP TABLE projects');
        $this->addSql('DROP TABLE time_params');
        $this->addSql('DROP TABLE users');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
