<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260525150802 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE investment_expense_categories (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(64) DEFAULT NULL, custom_title VARCHAR(255) DEFAULT NULL, related_expenses TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, investment_block_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B373CC0CD0515B10 ON investment_expense_categories (investment_block_id)');
        $this->addSql('ALTER TABLE investment_expense_categories ADD CONSTRAINT FK_B373CC0CD0515B10 FOREIGN KEY (investment_block_id) REFERENCES investment_blocks (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE investment_expense_categories DROP CONSTRAINT FK_B373CC0CD0515B10');
        $this->addSql('DROP TABLE investment_expense_categories');
    }
}
