<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260425115726 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE investment_blocks (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, financial_model_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX investment_blocks__financial_model_id__uniq ON investment_blocks (financial_model_id)');
        $this->addSql('CREATE TABLE investment_items (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, category VARCHAR(64) NOT NULL, title VARCHAR(255) DEFAULT NULL, initial_cost_rub NUMERIC(20, 2) NOT NULL, vat_applied BOOLEAN NOT NULL, useful_life_years INT DEFAULT NULL, deferred_expense_write_off_years INT DEFAULT NULL, lease_term_months INT DEFAULT NULL, depreciation_enabled BOOLEAN DEFAULT NULL, land_taxable BOOLEAN DEFAULT NULL, property_taxable BOOLEAN DEFAULT NULL, property_tax_base VARCHAR(32) DEFAULT NULL, cadastral_value_rub NUMERIC(20, 2) DEFAULT NULL, vehicle_taxable BOOLEAN DEFAULT NULL, vehicle_power_hp INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, investment_block_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8EDDDFB9D0515B10 ON investment_items (investment_block_id)');
        $this->addSql('ALTER TABLE investment_blocks ADD CONSTRAINT FK_7452604BD440FCE3 FOREIGN KEY (financial_model_id) REFERENCES financial_models (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE investment_items ADD CONSTRAINT FK_8EDDDFB9D0515B10 FOREIGN KEY (investment_block_id) REFERENCES investment_blocks (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER INDEX time_params__financial_model_id__uniq RENAME TO UNIQ_D6384105D440FCE3');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE investment_blocks DROP CONSTRAINT FK_7452604BD440FCE3');
        $this->addSql('ALTER TABLE investment_items DROP CONSTRAINT FK_8EDDDFB9D0515B10');
        $this->addSql('DROP TABLE investment_blocks');
        $this->addSql('DROP TABLE investment_items');
        $this->addSql('ALTER INDEX uniq_d6384105d440fce3 RENAME TO time_params__financial_model_id__uniq');
    }
}
