<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260427045108 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create Excel export jobs table.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE excel_exports (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(32) NOT NULL, file_path VARCHAR(255) DEFAULT NULL, error_message TEXT DEFAULT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, failed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, project_id BIGINT NOT NULL, financial_model_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX excel_exports__project_id__idx ON excel_exports (project_id)');
        $this->addSql('CREATE INDEX excel_exports__financial_model_id__idx ON excel_exports (financial_model_id)');
        $this->addSql('CREATE INDEX excel_exports__status_created_at__idx ON excel_exports (status, created_at)');
        $this->addSql('ALTER TABLE excel_exports ADD CONSTRAINT excel_exports__project_id__fk FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE excel_exports ADD CONSTRAINT excel_exports__financial_model_id__fk FOREIGN KEY (financial_model_id) REFERENCES financial_models (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE excel_exports DROP CONSTRAINT excel_exports__project_id__fk');
        $this->addSql('ALTER TABLE excel_exports DROP CONSTRAINT excel_exports__financial_model_id__fk');
        $this->addSql('DROP TABLE excel_exports');
    }
}
