<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260521173359 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE excel_exports DROP CONSTRAINT fk_8705bf2c166d1f9c');
        $this->addSql('DROP INDEX excel_exports__project_id__idx');
        $this->addSql('ALTER TABLE excel_exports DROP project_id');
        $this->addSql('ALTER TABLE financial_models DROP CONSTRAINT fk_4f766cba166d1f9c');
        $this->addSql('DROP INDEX financial_models__project_version_number__uniq');
        $this->addSql('DROP INDEX financial_models__project_id__idx');
        $this->addSql('DROP INDEX financial_models__project_id_status__idx');
        $this->addSql('ALTER TABLE financial_models DROP project_id');
        $this->addSql('ALTER TABLE projects DROP CONSTRAINT fk_5c93b3a47e3c61f9');
        $this->addSql('DROP TABLE projects');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE projects (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, short_id VARCHAR(10) NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, status VARCHAR(32) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, owner_id BIGINT NOT NULL, archived_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX projects__owner_id__idx ON projects (owner_id)');
        $this->addSql('CREATE INDEX projects__owner_id_status__idx ON projects (owner_id, status)');
        $this->addSql('CREATE UNIQUE INDEX projects__short_id__uniq ON projects (short_id)');
        $this->addSql('ALTER TABLE projects ADD CONSTRAINT fk_5c93b3a47e3c61f9 FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE excel_exports ADD project_id BIGINT DEFAULT NULL');
        $this->addSql('ALTER TABLE excel_exports ADD CONSTRAINT fk_8705bf2c166d1f9c FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX excel_exports__project_id__idx ON excel_exports (project_id)');
        $this->addSql('ALTER TABLE financial_models ADD project_id BIGINT DEFAULT NULL');
        $this->addSql('ALTER TABLE financial_models ADD CONSTRAINT fk_4f766cba166d1f9c FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE UNIQUE INDEX financial_models__project_version_number__uniq ON financial_models (project_id, version_number)');
        $this->addSql('CREATE INDEX financial_models__project_id__idx ON financial_models (project_id)');
        $this->addSql('CREATE INDEX financial_models__project_id_status__idx ON financial_models (project_id, status)');
    }
}
