<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260501151045 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE home (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, page_name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, btn_text VARCHAR(255) DEFAULT NULL, title TEXT DEFAULT NULL, keywords TEXT DEFAULT NULL, robots TEXT DEFAULT NULL, canonical VARCHAR(255) DEFAULT NULL, h1 VARCHAR(600) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE home');
    }
}
