<?php

declare(strict_types=1);

namespace App\Domain\Investments\Definition;

use App\Domain\Investments\Enum\InvestmentCategory;

final readonly class InvestmentCategoryDefinitions
{
    public static function for(InvestmentCategory $category): InvestmentCategoryDefinition
    {
        return match ($category) {
            InvestmentCategory::Land => new InvestmentCategoryDefinition(
                category: $category,
                titleRequired: true,
                vatApplicable: false,
                landTaxApplicable: true,
                propertyTaxApplicable: false,
                propertyTaxBaseApplicable: false,
                cadastralValueApplicable: true,
                vehicleTaxApplicable: false,
                vehiclePowerApplicable: false,
                usefulLifeYearsApplicable: false,
                deferredExpenseWriteOffYearsApplicable: false,
                leaseTermMonthsApplicable: false,
                depreciationChoiceApplicable: false,
            ),
            InvestmentCategory::Buildings => new InvestmentCategoryDefinition(
                category: $category,
                titleRequired: true,
                vatApplicable: true,
                landTaxApplicable: false,
                propertyTaxApplicable: true,
                propertyTaxBaseApplicable: true,
                cadastralValueApplicable: true,
                vehicleTaxApplicable: false,
                vehiclePowerApplicable: false,
                usefulLifeYearsApplicable: true,
                deferredExpenseWriteOffYearsApplicable: false,
                leaseTermMonthsApplicable: false,
                depreciationChoiceApplicable: false,
            ),
            InvestmentCategory::Equipment => new InvestmentCategoryDefinition(
                category: $category,
                titleRequired: true,
                vatApplicable: true,
                landTaxApplicable: false,
                propertyTaxApplicable: true,
                propertyTaxBaseApplicable: false,
                cadastralValueApplicable: false,
                vehicleTaxApplicable: false,
                vehiclePowerApplicable: false,
                usefulLifeYearsApplicable: true,
                deferredExpenseWriteOffYearsApplicable: false,
                leaseTermMonthsApplicable: false,
                depreciationChoiceApplicable: false,
            ),
            InvestmentCategory::FurnitureAndOfficeEquipment => new InvestmentCategoryDefinition(
                category: $category,
                titleRequired: true,
                vatApplicable: true,
                landTaxApplicable: false,
                propertyTaxApplicable: false,
                propertyTaxBaseApplicable: false,
                cadastralValueApplicable: false,
                vehicleTaxApplicable: false,
                vehiclePowerApplicable: false,
                usefulLifeYearsApplicable: true,
                deferredExpenseWriteOffYearsApplicable: false,
                leaseTermMonthsApplicable: false,
                depreciationChoiceApplicable: false,
            ),
            InvestmentCategory::Vehicles => new InvestmentCategoryDefinition(
                category: $category,
                titleRequired: true,
                vatApplicable: true,
                landTaxApplicable: false,
                propertyTaxApplicable: false,
                propertyTaxBaseApplicable: false,
                cadastralValueApplicable: false,
                vehicleTaxApplicable: true,
                vehiclePowerApplicable: true,
                usefulLifeYearsApplicable: true,
                deferredExpenseWriteOffYearsApplicable: false,
                leaseTermMonthsApplicable: false,
                depreciationChoiceApplicable: false,
            ),
            InvestmentCategory::IntangibleAssets => new InvestmentCategoryDefinition(
                category: $category,
                titleRequired: true,
                vatApplicable: true,
                landTaxApplicable: false,
                propertyTaxApplicable: false,
                propertyTaxBaseApplicable: false,
                cadastralValueApplicable: false,
                vehicleTaxApplicable: false,
                vehiclePowerApplicable: false,
                usefulLifeYearsApplicable: true,
                deferredExpenseWriteOffYearsApplicable: false,
                leaseTermMonthsApplicable: false,
                depreciationChoiceApplicable: false,
            ),
            InvestmentCategory::LeaseholdImprovements => new InvestmentCategoryDefinition(
                category: $category,
                titleRequired: false,
                vatApplicable: true,
                landTaxApplicable: false,
                propertyTaxApplicable: true,
                propertyTaxBaseApplicable: false,
                cadastralValueApplicable: false,
                vehicleTaxApplicable: false,
                vehiclePowerApplicable: false,
                usefulLifeYearsApplicable: false,
                deferredExpenseWriteOffYearsApplicable: false,
                leaseTermMonthsApplicable: true,
                depreciationChoiceApplicable: false,
            ),
            InvestmentCategory::OtherCapitalized => new InvestmentCategoryDefinition(
                category: $category,
                titleRequired: false,
                vatApplicable: true,
                landTaxApplicable: false,
                propertyTaxApplicable: false,
                propertyTaxBaseApplicable: false,
                cadastralValueApplicable: false,
                vehicleTaxApplicable: false,
                vehiclePowerApplicable: false,
                usefulLifeYearsApplicable: true,
                deferredExpenseWriteOffYearsApplicable: false,
                leaseTermMonthsApplicable: false,
                depreciationChoiceApplicable: true,
            ),
            InvestmentCategory::InitialInventory => new InvestmentCategoryDefinition(
                category: $category,
                titleRequired: false,
                vatApplicable: true,
                landTaxApplicable: false,
                propertyTaxApplicable: false,
                propertyTaxBaseApplicable: false,
                cadastralValueApplicable: false,
                vehicleTaxApplicable: false,
                vehiclePowerApplicable: false,
                usefulLifeYearsApplicable: false,
                deferredExpenseWriteOffYearsApplicable: false,
                leaseTermMonthsApplicable: false,
                depreciationChoiceApplicable: false,
            ),
            InvestmentCategory::DeferredMarketingAndTraining => new InvestmentCategoryDefinition(
                category: $category,
                titleRequired: false,
                vatApplicable: true,
                landTaxApplicable: false,
                propertyTaxApplicable: false,
                propertyTaxBaseApplicable: false,
                cadastralValueApplicable: false,
                vehicleTaxApplicable: false,
                vehiclePowerApplicable: false,
                usefulLifeYearsApplicable: false,
                deferredExpenseWriteOffYearsApplicable: true,
                leaseTermMonthsApplicable: false,
                depreciationChoiceApplicable: false,
            ),
            InvestmentCategory::OtherDeferredExpense => new InvestmentCategoryDefinition(
                category: $category,
                titleRequired: false,
                vatApplicable: true,
                landTaxApplicable: false,
                propertyTaxApplicable: false,
                propertyTaxBaseApplicable: false,
                cadastralValueApplicable: false,
                vehicleTaxApplicable: false,
                vehiclePowerApplicable: false,
                usefulLifeYearsApplicable: false,
                deferredExpenseWriteOffYearsApplicable: true,
                leaseTermMonthsApplicable: false,
                depreciationChoiceApplicable: false,
            ),
        };
    }
}
